In [2]:
print("Hello World!")

Hello World!


In [2]:
print("Hello World!")

Hello World!


In [9]:
print("Hello World!")

Hello World!


In [10]:
i=1
while i<=15:
    print(i)
    i=i+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [12]:
print("hello")

hello


In [13]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [14]:
!pip install numpy

In [15]:
import numpy as np

In [53]:
array1=(np.random.rand(2,4))

In [65]:
array1[0:1]

array([[0.22743193, 0.49941213, 0.82332496, 0.44477986]])

In [21]:
a="sammy"
print(a)

sammy


In [22]:
print(a)

sammy


In [24]:
Chika=[33,45,34,23,45]
print(type(Chika))

<class 'list'>


In [25]:
Manan = np.array(Chika)
print(type(Manan))

<class 'numpy.ndarray'>


In [25]:
Manan = np.array(Chika)
print(type(Manan))

<class 'numpy.ndarray'>


In [30]:
print(b)

beta


In [31]:
print(b)zzzz

beta


In [34]:
arr1=np.array([3,5,7])
arr2=np.array([9,11,13])
print(arr2)
arr1

[ 9 11 13]


array([3, 5, 7])

In [35]:
a=[3,45,4]
print(a)

[3, 45, 4]


In [36]:
print(Manan[-1])

45


In [16]:
CE2 = ["Efo","Manan","Eunice","Hajara"]
List2 = CE2[1:4]
CE_Females = "Samuella","Enyonam","Janet"
for name in CE2 or CE_Females:
    print(name)

Efo
Manan
Eunice
Hajara


In [19]:
!pip install numpy

In [21]:
#cell containing libraries
import numpy as np


In [22]:
List1 = [1,2,3,4,5]
print(type(List1))

List2 = [[1,2,3],[5,6,7]]
print(type(List2))

Listnp = np.array(List1)
print(type(Listnp))



list

# Pandas Basics 

In [38]:
##Reading CSV file

import pandas as pd

df = pd.read_csv("analcatdata_bankruptcy.csv")

print(df.head())


FileNotFoundError: [Errno 2] No such file or directory: 'analcatdata_bankruptcy.csv'

In [39]:
!pip install pandas

In [40]:
import pandas as pd

df = pd.read_csv("analcatdata_bankruptcy.csv")

pn df.sha

SyntaxError: invalid syntax (Temp/ipykernel_12276/2346916068.py, line 6)

# Building a linear regression model using the OLS Model


#Importing the relevant libraries 

In [5]:
import numpy as np , pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

In [8]:
# loading the dataset into the dataframe

Dframe = pd.read_csv ("diamond.csv")
Dframe.head()


Unnamed: 0  carat colour clarity certification  price
0           1   0.30      D     VS2           GIA   1302
1           2   0.30      E     VS1           GIA   1510
2           3   0.30      G    VVS1           GIA   1510
3           4   0.30      G     VS1           GIA   1260
4           5   0.31      D     VS1           GIA   1641

In [9]:
Dframe.head()

Unnamed: 0  carat colour clarity certification  price
0           1   0.30      D     VS2           GIA   1302
1           2   0.30      E     VS1           GIA   1510
2           3   0.30      G    VVS1           GIA   1510
3           4   0.30      G     VS1           GIA   1260
4           5   0.31      D     VS1           GIA   1641

In [11]:
# With OLS models we need two variables 
#Let X be a column in the dataframe 
X = Dframe.carat
X1 = Dframe["carat"]
# We need to declare two variables for x because one will be assigned the constant 
print (X.head())

0    0.30
1    0.30
2    0.30
3    0.30
4    0.31
Name: carat, dtype: float64


In [9]:
Y = Dframe.price
print(Y.head())


NameError: name 'Dframe1' is not defined

In [13]:
#Adding constant to the independent variable
X= sm.add_constant(X)
print(X.head())

   const  carat
0    1.0   0.30
1    1.0   0.30
2    1.0   0.30
3    1.0   0.30
4    1.0   0.31


C:\Users\scraTch\Anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [6]:
#Create a variable to hold the model
OLS_LINEAR_REGRESSION = sm.OLS(endog = Y, exo = X).fit()

NameError: name 'Y' is not defined

In [1]:
OLS_LINEAR_REGRESSION ending.summary

SyntaxError: invalid syntax (Temp/ipykernel_2660/1850632377.py, line 1)

In [2]:
print (OLS_LINEAR_REGRESSION.summary())

NameError: name 'OLS_LINEAR_REGRESSION' is not defined